"""Add user audit foreign keys

Revision ID: 5f66e7932b1e
Revises: fa25577a9815
Create Date: 2026-08-09 19:50:56.720318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f66e7932b1e'
down_revision: Union[str, Sequence[str], None] = 'fa25577a9815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'login_history', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'login_history', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'permissions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'permissions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_sessions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_sessions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    # ### end Alembic commands ###
