"""Add cascade to UserRole foreign keys

Revision ID: 69e58f13cba3
Revises: 9f9bdf9ded13
Create Date: 2026-08-10 13:52:42.711211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e58f13cba3'
down_revision: Union[str, Sequence[str], None] = '9f9bdf9ded13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
