"""Update authentication models

Revision ID: 9f9bdf9ded13
Revises: 5f66e7932b1e
Create Date: 2026-08-10 13:32:59.908239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f9bdf9ded13'
down_revision: Union[str, Sequence[str], None] = '5f66e7932b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', type_='unique')
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'email_verification_tokens', ['token_hash'])
    op.drop_column('email_verification_tokens', 'used')
    op.drop_column('email_verification_tokens', 'token')
    op.add_column('login_history', sa.Column('login_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('login_history', sa.Column('is_successful', sa.Boolean(), nullable=False))
    op.alter_column('login_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('login_history_user_id_fkey'), 'login_history', type_='foreignkey')
    op.create_foreign_key(None, 'login_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('login_history', 'login_time')
    op.drop_column('login_history', 'successful')
    op.add_column('password_reset_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'password_reset_tokens', ['token_hash'])
    op.drop_column('password_reset_tokens', 'used')
    op.drop_column('password_reset_tokens', 'token')
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('replaced_by_token_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_token_id'], ['id'], ondelete='SET NULL')
    op.drop_column('refresh_tokens', 'token')
    op.drop_column('refresh_tokens', 'revoked')
    op.add_column('user_sessions', sa.Column('session_id', sa.String(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('user_sessions', sa.Column('device_name', sa.String(length=100), nullable=True))
    op.add_column('user_sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('user_sessions_jti_key'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'user_sessions', ['refresh_token_id'])
    op.drop_column('user_sessions', 'revoked')
    op.drop_column('user_sessions', 'device_info')
    op.drop_column('user_sessions', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('device_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.create_unique_constraint(op.f('user_sessions_jti_key'), 'user_sessions', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'last_activity_at')
    op.drop_column('user_sessions', 'device_name')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'session_id')
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'replaced_by_token_id')
    op.drop_column('refresh_tokens', 'revoked_at')
    op.drop_column('refresh_tokens', 'token_hash')
    op.add_column('password_reset_tokens', sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('password_reset_tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('password_reset_tokens', 'used_at')
    op.drop_column('password_reset_tokens', 'token_hash')
    op.add_column('login_history', sa.Column('successful', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('login_history', sa.Column('login_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.create_foreign_key(op.f('login_history_user_id_fkey'), 'login_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.alter_column('login_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('login_history', 'is_successful')
    op.drop_column('login_history', 'login_at')
    op.add_column('email_verification_tokens', sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('email_verification_tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email_verification_tokens', type_='unique')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.create_unique_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('email_verification_tokens', 'verified_at')
    op.drop_column('email_verification_tokens', 'token_hash')
    # ### end Alembic commands ###
